name: publish
on:
  release:
    types: [published]

jobs:
  unit-tests-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
      - name: setup deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.34.3
      - name: build
        run: deno run -A build.ts
      - name: publish
        run: npm publish
        working-directory: npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

