name: unit tests
on: [push]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 18, 20 ]
    steps:
      - uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: setup deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.34.3
      - name: build
        run: |
          rm -f deno.lock \
          deno cache --reload mod.ts \
          deno run -A build.ts
      - name: tests(node)
        run: deno task test:node
      - name: tests(deno)
        run: deno task test:deno

